apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: hello-tekton-app-anil
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: hello-app-trigger-anil
  resources:
    kubernetesResource:
      serviceType: NodePort    
