apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: complete-task-anil
spec:
  steps:
    - name: echo
      image: alpine
      script: |
        #!/bin/sh
        echo ">>>>>>>>>>>>>>>> Pipeline Completed Successfully!!!!! <<<<<<<<<<<<<<<<<<<"       